sudo: false
language: rust
rust:
- 1.22.0  # Oldest supported
- stable
- beta
- nightly

matrix:
  include:
  - env: CLIPPY_VERSION=0.0.179
    rust: nightly-2018-01-12
    install:
    - travis_wait cargo install clippy --version $CLIPPY_VERSION || echo "clippy already installed"
    script:
    - cargo clippy -- -D clippy

install:
- rustc -Vv
- cargo -V

script:
- cargo test --verbose

cache:
  cargo: true
